function validation_OK = ...
  ValidateMaxRelativeValueDifference(base_path_reference, base_path_test, ...
                                     reference_name_root, test_name_root, ...
                                     acceptable_error)
% Function for regression test of binary files
validation_OK = false;
if ~compareBinFiles([base_path_reference reference_name_root '_f0.bin'], ...
                    [base_path_test test_name_root '_f0.bin'], ...
                    acceptable_error)
  return;
end;
if ~compareBinFiles([base_path_reference reference_name_root '_vuv.bin'], ...
                    [base_path_test test_name_root '_vuv.bin'], ...
                    acceptable_error)
  return;
end;
if ~compareBinFiles([base_path_reference reference_name_root '_ap.bin'], ...
                    [base_path_test test_name_root '_ap.bin'], ...
                    acceptable_error)
  return;
end;
if ~compareBinFiles([base_path_reference reference_name_root '_sp.bin'], ...
                    [base_path_test test_name_root '_sp.bin'], ...
                    acceptable_error)
  return;
end;
validation_OK = true;
end

function validation_OK = ...
  compareBinFiles(filename1, filename2, acceptable_error)
validation_OK = false;
data_ref = ReadMatrix(filename1);
data_test = ReadMatrix(filename2);
if ~prod(size(data_ref) == size(data_test))
  return;
elseif max(abs(data_ref(:)-data_test(:))) / max(abs(data_ref(:))) > ...
    acceptable_error
  return;
end;
validation_OK = true;
end
